# Generated by Django 4.1.7 on 2023-03-07 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=14)),
                ('upload', models.ImageField(upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name_plural': 'Profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
