# Generated by Django 3.2.13 on 2023-03-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0003_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
    ]
