# Generated by Django 3.2.13 on 2023-03-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0004_alter_profile_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='upload',
            field=models.ImageField(upload_to='media'),
        ),
    ]
